#servicios
services:
    # chatbot:
    #   build:
    #     context: chatbot/          # ruta donde está tu Dockerfile
    #     dockerfile: Dockerfile
    #   container_name: elpicantito-chat
    #   ports:
    #     - "8501:8501"
      
  #crear bases de datos 
    db:
      image: postgres:16.1
      container_name: ElPicantitoDB
      restart: always
      volumes:
      # Volumen para persistencia de datos (no montamos todo ./sql para evitar ejecutar scripts no deseados)
      # Montamos solo el archivo create_schema.sql en el init folder para que SOLO ese script se ejecute en la inicialización.
        - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql:ro
        - postgres_data:/var/lib/postgresql/data  # Volumen nombrado para datos persistentes
      environment:
      ## informacion de bases de datos
        POSTGRES_DB: 'picantitodb'
        POSTGRES_USER: 'taquito'
        POSTGRES_PASSWORD: 'taquito123'
      ports:
        - '5432:5432'

# Definición de volúmenes nombrados para persistencia de datos
volumes:
  postgres_data: